language: c

sudo: false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - bison
      - flex
      - valgrind

before_install:
  - script/bootstrap

script:
  - script/cibuild

git:
  depth: 10
