version: '{build}'
clone_depth: 10
environment:
  PYTHON: "C:\\Python34-x64"
  PYTHON_VERSION: "3.4.3"
  PYTHON_ARCH: "64"
  matrix:
  - GENERATOR: "Visual Studio 13"
    ARCH: 32
  - GENERATOR: "Visual Studio 13"
    ARCH: 64
  - GENERATOR: "Visual Studio 11"
    ARCH: 32
  - GENERATOR: "Visual Studio 11 Win64"
    ARCH: 64
  - GENERATOR: "MSYS Makefiles"
    ARCH: 32
  - GENERATOR: "MSYS Makefiles"
    ARCH: i686 # this is for 32-bit MinGW-w64
  - GENERATOR: "MSYS Makefiles"
    ARCH: 64
build_script:
- ps: |
    mkdir build
    cmake . -Bbuild
    msbuild /p:Configuration=Release build/mtex2MML.sln
test_script:
- ps: build\Release\mtex2MML_clar.exe
