version: '{build}'
clone_depth: 10
environment:
  PYTHON: "C:\\Python34-x64"
  PYTHON_VERSION: "3.4.3"
  PYTHON_ARCH: "64"
  matrix:
  - GENERATOR: "Visual Studio 13"
    ARCH: 32
  - GENERATOR: "Visual Studio 13"
    ARCH: 64
build_script:
- ps: |
    mkdir build
    cmake . -Bbuild
    msbuild /p:Configuration=Release build/mtex2MML.sln
test_script:
- ps: build\Release\mtex2MML_clar.exe
