name: Test

on:
  workflow_dispatch:
  pull_request_target:

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        name: Install *nix dependencies
        run: script/bootstrap

      - if: matrix.os == 'windows-latest'
        name: Install Windows dependencies
        run: choco install winflexbison

      - if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        name: Run tests
        run: script/cibuild
